CREATE TABLE IF NOT EXISTS cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    email VARCHAR(255),
    telefone VARCHAR(255),
    endereco VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS vendedor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    data_nascimento DATE
);

CREATE TABLE IF NOT EXISTS produto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    preco NUMERIC(38, 2),
    quantidade INTEGER
);

CREATE TABLE IF NOT EXISTS pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES cliente (id),
    vendedor_id BIGINT REFERENCES vendedor (id),
    data_pedido DATE,
    forma_pagamento VARCHAR(255),
    status_pedido VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS item_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT REFERENCES pedido (id),
    produto_id BIGINT REFERENCES produto (id),
    quantidade INTEGER,
    valor_unitario NUMERIC(38, 2)
);
